# Site address that will be used by the server. Necessary for the HTTPS
# certificates.
domain: example.com

# SSL certificate to use with HTTPS. This parameter is optional and if it is not
# provided, a new certificate will be issued using Let's encrypt.
# ssl: "./example.com.cert"

# Custom error pages to use in case a user tries to access an unknown file,
# protected file or there is a server error.
# pages:
#   403: "./_403.html"  
#   404: "./_404.html"
#   500: "./_500.html"

# Enables the automatic rendering of markdown files (.md) into styled HTML. 
markdown: true
  
# Enables a HTTP endpoint to use locally.
development: false

# Enables SPA mode. It will redirect any non matched route to the index.html of
# the root folder.
spa: true

# Enables basic file browser to display the contents of a folder in case there
# is no index.html file in the 
ui: true

# Protects certains paths from being accessed unless a valid user and password
# is provided. The combination of hash(user:password) needs to match one in the
# list.
authorization:
  - path: "/secret-place"
    algorithm: "md5"
    auth:
      - validhash
      - validhash

# TODO: Future features.
# form: false
# stats: false

# admin:
#   user: admin
#   pass: pass
